<?xml version="1.0" encoding="utf-8" ?>
<Project>
  <PropertyGroup>
	
     <TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('windows'))">$(TargetFrameworks);net8.0-windows10.0.19041.0</TargetFrameworks>
     <Nullable>enable</Nullable>
     <ImplicitUsings>enable</ImplicitUsings>
	 <Platforms>AnyCPU;x64</Platforms>
	 <Copyright>Copyright 2023 TKE</Copyright>	
	<ProductName>ConfigTool</ProductName>
	<Company>thyssenkrupp</Company>
	<ApplicationDisplayVersion>1.8.6</ApplicationDisplayVersion>
    <ApplicationVersion>1</ApplicationVersion>
  </PropertyGroup>
  
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <OutputPath>$(SolutionDir)\bin</OutputPath>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <OutputPath>$(SolutionDir)\bin</OutputPath>
  </PropertyGroup>
  
</Project>